---
title: "Week3 Quiz"
author: "Bijan Ranjbar-Sahraei"
date: "August 17, 2015"
output: html_document
---

# Question 1
```{r}
library(AppliedPredictiveModeling)
data(segmentationOriginal)
library(caret)

training <- segmentationOriginal[segmentationOriginal$Case == "Train",]
testing <- segmentationOriginal[segmentationOriginal$Case == "Test",]

set.seed(125)
modFit <- train(Class~., method="rpart", data=training) 
modFit$finalModel
library(rattle)
fancyRpartPlot(modFit$finalModel)

```

# Question 2

# Question 3
```{r}
library(pgmm)
data(olive)
olive = olive[,-1]
training <- olive  # I skip partitioning the data!
modFit <- train(Area~., method="rpart", data=training) 
newdata <- as.data.frame(t(colMeans(olive)))
pred <- predict(modFit,newdata)
```

# Question 4
```{r}
library(ElemStatLearn)
data(SAheart)
set.seed(8484)
train = sample(1:dim(SAheart)[1],size=dim(SAheart)[1]/2,replace=F)
trainSA = SAheart[train,]
testSA = SAheart[-train,]

set.seed(13234)
modFit <- train(chd ~ age+alcohol+obesity+tobacco+typea+ldl,
                method="glm",  
                data=trainSA,
                family="binomial"
                )
```
Here we calculate the miss classification
```{r}
missClass = function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}
missClass(trainSA$chd,predict(modFit,trainSA))
missClass(testSA$chd,predict(modFit,testSA))
```

# Question 5
```{r}
library(ElemStatLearn)
data(vowel.train)
data(vowel.test)

head(vowel.train)
head(vowel.test)
```
Set the variable y to be a factor variable in both the training and test set.

```{r}
vowel.train$y <- as.factor(vowel.train$y)
vowel.test$y <- as.factor(vowel.test$y)

head(vowel.train)
head(vowel.test)
set.seed(33833)
modFit <- train(y ~.,data=vowel.train,method="rf")

varImp(modFit)

```
